# Generated by Django 3.2.12 on 2022-04-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_auto_20220220_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=1024)),
                ('frame', models.PositiveIntegerField()),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_param', to='engine.data')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
