# Generated by Django 3.2.12 on 2022-04-02 07:41

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0052_cameraparam'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedCameraParamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(max_length=1024, storage=cvat.apps.engine.models.MyFileSystemStorage(), upload_to=cvat.apps.engine.models.upload_path_handler)),
                ('data', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_camera_files', to='engine.data')),
                ('primary_camera_param', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_camera_files', to='engine.cameraparam')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('data', 'path')},
            },
        ),
    ]
